version: '3.7'
services:
  postgres:
    image: postgres:13-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments_db

  rabbitmq:
    image: rabbitmq:3.9.7
    ports:
      - 5674:5672
      - 15674:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
